import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";
import sharp from "sharp";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

function toPlainText(html) {
  return html
    .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, " ")
    .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&quot;/g, '"')
    .replace(/(?:&#x27;|&#39;|&apos;)/g, "'")
    .replace(/&amp;/g, "&")
    .replace(/&nbsp;/g, " ")
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/\s+/g, " ")
    .trim();
}

function sliceBetween(text, start, end) {
  const startIndex = text.indexOf(start);
  const endIndex = text.indexOf(end, startIndex + start.length);
  assert.ok(startIndex >= 0, `Missing section marker: ${start}`);
  assert.ok(endIndex > startIndex, `Missing or misordered marker: ${end}`);
  return text.slice(startIndex, endIndex);
}

test("server-renders the AgentBait paper site", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  const plainText = toPlainText(html);
  assert.match(html, /<title>You Won(?:&#x27;|')t Believe This Click: Content Rewriting for Agentic Choice<\/title>/i);
  assert.match(html, /<meta name="description" content="AgentBait studies how rewriting the presentation of one content item can shift language-model-mediated selection, and examines the trade-off between selection and factual support\."\/>/);
  assert.match(html, /<meta name="robots" content="index, follow, max-image-preview:large"\/>/);
  assert.match(html, /<link rel="canonical" href="https:\/\/agentbait\.github\.io\/"\/>/);
  assert.ok((html.match(/GTM-WSHC2PFG/g) || []).length >= 2, "GTM container must appear in both script and noscript fallbacks");
  assert.match(html, /googletagmanager\.com\/gtm\.js\?id=/);
  assert.match(html, /googletagmanager\.com\/ns\.html\?id=GTM-WSHC2PFG/);
  assert.match(html, /<h1 id="paper-title">You Won(?:&#x27;|')t Believe This Click<\/h1>/);
  assert.doesNotMatch(html, /class="click-word"|Complete the word Click|click-placeholder|Click, selected/);
  assert.doesNotMatch(plainText, /Research feature/i);
  assert.doesNotMatch(plainText, /01 · Agent-legible presentation effects/i);
  assert.doesNotMatch(plainText, /Does a better presentation become a different decision\?/);
  assert.match(plainText, /You Won't Believe This Click Content Rewriting for Agentic Choice/);
  assert.match(plainText, /Can changing only one item's presentation change the chooser's decision\?/);
  assert.equal((plainText.match(/Can changing only one item's presentation change the chooser's decision\?/g) || []).length, 1);
  assert.doesNotMatch(plainText, /We rewrite one target item's title and abstract, then ask the same LLM chooser to select again from the same candidate list\./);
  assert.doesNotMatch(plainText, /Target selection with a learned advisor/);
  assert.doesNotMatch(plainText, /We train an advisor to guide a frozen rewriter toward texts that an LLM agent is more likely to select/);
  assert.doesNotMatch(html, /Small textual rewrites can systematically manipulate LLM-based recommendation agents/);
  assert.doesNotMatch(html, /Interactive Figure 1|Eleven-second fixed-set chooser replay|Auto play/);
  assert.doesNotMatch(html, /Scene [1-7] ·/);
  assert.match(html, /Automatically animated AgentBait fixed-slate comparison/);
  assert.doesNotMatch(html, /Run AgentBait|Replay AgentBait/);
  assert.match(html, /Candidate Set/);
  assert.doesNotMatch(html, /Three fixed MIND snippets/);
  assert.match(html, /Marshawn playing in charity soccer game went exactly as you/);
  assert.match(html, /Sofia Vergara and Joe Manganiello Celebrate/);
  assert.match(html, /The Coolest And Craziest McDonald/);
  assert.match(plainText, /If there was ever a sport-athlete combination that we'd never expect to work out, it'd be Marshawn Lynch dabbling in soccer\./);
  assert.match(plainText, /Sometimes, the Golden Arches know how to pull out all the stops\./);
  assert.equal((html.match(/class="paper-abstract"/g) || []).length, 3);
  assert.equal((plainText.match(/Abstract/g) || []).length >= 3, true);
  assert.match(html, /Before/);
  assert.match(html, /Click B/);
  assert.match(html, /Click A/);
  assert.match(html, /MiniCheck/);
  assert.doesNotMatch(html, /The cards do not move\. The chooser does\./);
  assert.match(html, /class="hero-feature"/);
  assert.doesNotMatch(html, /hero-result-summary|Results at a glance|01 · Core effect/);
  assert.doesNotMatch(html, /news-thumb/);
  assert.doesNotMatch(html, /clearer framing|stronger relevance|same underlying content/i);
  assert.doesNotMatch(html, /Original baseline|Rewriting outcomes with and without MiniCheck/);
  assert.doesNotMatch(plainText, /Research question/);
  assert.doesNotMatch(html, /Agent-mediated information access|Working paper · July 2026/);
  assert.doesNotMatch(html, /class="margin-note numbered-note"/);
  assert.match(html, /Examples as editorial redlines/);
  const abstractText = sliceBetween(plainText, "02 · Abstract", "03 · Key findings");
  const findingsText = sliceBetween(plainText, "03 · Key findings", "04 · Interactive setting");
  const settingText = sliceBetween(plainText, "04 · Interactive setting", "05 · Examples as editorial redlines");
  assert.ok(plainText.indexOf("02 · Abstract") < plainText.indexOf("03 · Key findings"));
  assert.ok(plainText.indexOf("03 · Key findings") < plainText.indexOf("04 · Interactive setting"));
  assert.ok(plainText.indexOf("04 · Interactive setting") < plainText.indexOf("05 · Examples as editorial redlines"));
  assert.ok(plainText.indexOf("05 · Examples as editorial redlines") < plainText.indexOf("Table 1 · Target-agent transfer"));
  assert.ok(plainText.indexOf("Table 2 · Source-support tradeoff") < plainText.indexOf("06 · Robustness, transfer and failure"));
  assert.ok(plainText.indexOf("06 · Robustness, transfer and failure") < plainText.indexOf("Table 3 · Language transfer"));
  assert.ok(plainText.indexOf("06 · Robustness, transfer and failure") < plainText.indexOf("07 · BibTeX"));
  assert.doesNotMatch(plainText, /07 · Methods/);
  assert.doesNotMatch(plainText, /How to read|Struck text is displaced source framing/);
  assert.doesNotMatch(plainText, /Strategy audit|unfaithful technical pivot/);

  const formalAbstractParts = [
    "Language models are increasingly used as agents to help humans decide what information is surfaced. This usage incentivizes content creators to optimize content in ways that appeal not only to humans, but also to agents that mediate access to them. In this paper, we study selection shifts induced by rewriting in agentic decision-making. Given a set of competing content snippets, we rewrite only one snippet while leaving the rest unchanged, and then measure how it impacts the agent's choice.",
    "We operationalize this setup with AgentBait, an advisor-rewriter framework in which the advisor learns to propose rewriting strategies and the rewriter revises the snippet. While a rewriter with a fixed prompt improves target snippet selection from 17.1% to 34.8%, our AgentBait raises its selection to 98.5%. We further show that the advisor trained with AgentBait effectively transfers to setups with different agents, languages, and snippets in other domains (e.g., scientific papers).",
    "However, higher target selection can reflect unsupported rewrites rather than better content. Adding a reward for support from the original snippet redirects the advisor toward more supported rewriting strategies, revealing a trade-off between factuality and target selection. Together, our results show that once agents mediate access to information, content can be rewritten to be chosen by the agent, even when selection and usefulness diverge.",
  ];
  for (const paragraph of formalAbstractParts) assert.ok(abstractText.includes(paragraph), `Formal Abstract paragraph is missing or altered: ${paragraph.slice(0, 70)}…`);
  assert.doesNotMatch(abstractText, /"Preference" refers only to observed choices under the same prompt and candidate list/);
  assert.doesNotMatch(abstractText, /Observed choice, not intrinsic quality/i);

  assert.match(settingText, /Same slate\. One rewrite\. Can the decision change\?/);
  assert.match(settingText, /The candidate list has already been constructed\. Only the target presentation may change\./);
  assert.doesNotMatch(html, /Only the target text changes\. The candidate set and chooser conditions remain fixed\./);
  assert.match(html, /data-graph-view="narrative"/);
  assert.match(html, /\/paper-method-transparent\.png/);
  assert.match(html, /AgentBait narrative pipeline: a target document is selected from a fixed candidate slate/);
  assert.match(html, /class="graph-view-toggle"/);
  assert.match(html, /Paper graph/);
  assert.match(html, /Advisor–rewriter setting/);
  assert.match(html, /πθ\(s \| xB\) · target only/);
  assert.match(html, /xB \+ s → x′B/);
  assert.match(html, /Original · unselected/);
  assert.match(html, /Rewritten target/);
  assert.match(html, /Rewritten · selected/);
  assert.match(html, /Overview of our target-only advisor–rewriter setting\./);
  assert.doesNotMatch(html, /Held constant across conditions|Slate size|Non-target text|Chooser prompt/);
  assert.match(html, /Advisor/);
  assert.match(html, /Rewriter/);
  assert.match(html, /Selection/);
  assert.match(html, /Advisor suggests/);
  assert.match(settingText, /Receives only the extracted target document and proposes a rewriting strategy\./);
  assert.match(settingText, /Applies the strategy to the target title and abstract only\./);
  assert.match(settingText, /Selects from the same candidate identities and order, with only the target rewritten\./);
  assert.match(settingText, /Try a sharper, more specific framing\./);
  assert.match(settingText, /Push the hook further, but keep it specific\./);
  assert.match(html, /AgentBait process: read the target, edit it, then select from the fixed slate/);
  assert.match(html, /Outside advisor · fixed slate/);
  assert.match(html, /Advisor input · target only/);
  assert.equal((settingText.match(/Advisor input/g) || []).length, 1);
  assert.doesNotMatch(html, /advisor-input-boundary"><i>Advisor input/);
  assert.match(html, /The advisor and frozen rewriter receive only the extracted target document; only the target agent sees the full fixed slate\./);
  assert.doesNotMatch(html, /advisor-candidates|Candidate set read by the advisor/);
  assert.match(html, /MiniCheck sentence support/);
  assert.match(settingText, /Selection outcome/);
  assert.match(settingText, /Reward/);
  assert.match(settingText, /GRPO updates the advisor policy/);
  assert.match(settingText, /01 · Target input Trained Advisor/);
  assert.match(settingText, /02 · Edit Frozen Frozen Rewriter/);
  assert.match(settingText, /03 · Select Frozen Target Agent/);
  assert.doesNotMatch(settingText, /RL feedback loop|Rewriter · Frozen|Chooser · Frozen|Advisor · Trained/);
  assert.match(html, /\/advisor-scholar\.png/);
  assert.match(html, /\/selector-hand\.png/);
  assert.match(html, /The learned advisor transfers across languages/);
  assert.match(html, /The effect extends beyond the training dataset/);
  assert.match(html, /Cross-domain transfer is harder, but remains substantial/);
  assert.match(html, /SciRepEval-derived scientific documents/);
  assert.match(html, /63\.6/);
  assert.match(html, /47\.3/);
  assert.doesNotMatch(html, /Cross-target-agent mismatch/);
  const sensitivity = sliceBetween(findingsText, "01 Sensitivity", "02 Optimization");
  const optimization = sliceBetween(findingsText, "02 Optimization", "03 Shortcut");
  const shortcut = sliceBetween(findingsText, "03 Shortcut", "04 Source support");
  const sourceSupport = findingsText.slice(findingsText.indexOf("04 Source support"));
  assert.match(findingsText, /How presentation becomes a decision signal/);
  assert.match(findingsText, /Agent-mediated selection creates a direct optimization pressure on content presentation\./);
  assert.match(sensitivity, /Presentation shifts choice/);
  assert.match(sensitivity, /17\.1%/);
  assert.match(sensitivity, /34\.8%/);
  assert.match(sensitivity, /Original/);
  assert.match(sensitivity, /Prompt rewrite/);
  assert.match(optimization, /Agent feedback makes the pressure learnable/);
  assert.match(optimization, /34\.8%/);
  assert.match(optimization, /98\.5%/);
  assert.match(optimization, /Prompt rewrite/);
  assert.match(optimization, /Trained advisor/);
  assert.match(shortcut, /Selection-only rewards discover unsupported shortcuts/);
  assert.match(shortcut, /98\.5%/);
  assert.match(shortcut, /2\.0%/);
  assert.match(sourceSupport, /Source support changes what the optimizer learns/);
  assert.match(sourceSupport, /68\.6%/);
  assert.match(sourceSupport, /Unsupported technical substitution/);
  assert.match(sourceSupport, /96\.2%/);
  assert.match(sourceSupport, /0\.1%/);
  assert.doesNotMatch(findingsText, /03 Transfer|The learned advice generalizes|Training amplifies the effect/);
  assert.match(shortcut, /Selected/);
  assert.match(shortcut, /Supported/);
  assert.doesNotMatch(findingsText, /Four conclusions from the controlled comparison|Finding [1-4]|Presentation alone changes agent decisions|Constraints change what the advisor learns/i);
  assert.doesNotMatch(findingsText, /The effect travels|Across agents|Across languages|From news to scientific-paper selection/i);
  assert.doesNotMatch(html, /Evidence table [12]|Complete target-agent comparison|Target selection under original and rewritten presentations|Selection and source support under rewriting|Cross-lingual transfer on fixed MIND slates|Transfer across news datasets|Transfer to academic document selection/);
  const tableTakeaways = [
    "Prompt-only rewriting raises target selection from 17.1% to 34.8%, while the RL-trained advisor reaches 98.5%. Gains remain positive across all held-out target agents, although transfer strength varies.",
    "The unconstrained advisor reaches 98.5% target selection with only 2.0% MiniCheck support. Adding a source-support reward partially recovers support while reducing selection.",
    "Trained only on English MIND, the advisor remains above 93% selection in every evaluated language without additional training. Direct rewriter training is less stable, falling to 27.8% in Swahili.",
    "Without additional training, the advisor reaches 98.1% on EB-NeRD English and 98.2% on EB-NeRD Danish. The result therefore extends beyond translation of the original MIND evaluation set.",
    "On scientific-document selection, the MIND-trained advisor reaches 63.6%, compared with 42.7% for the prompt-only advisor and 32.7% for the RL-trained direct rewriter.",
  ];
  for (const takeaway of tableTakeaways) assert.ok(plainText.includes(takeaway), `Table takeaway is missing or altered: ${takeaway.slice(0, 70)}…`);
  assert.doesNotMatch(html, /Full experimental table|collapse \/ expand/);
  assert.doesNotMatch(html, /A different decision|unchanged candidate slate|Policy updated: sharpen specificity|before advisor training begins|factual quality|reward \+ constraint|final evaluation rubric|Attack strategy 0[12]/i);
  assert.doesNotMatch(plainText, /Same slate · Both selected/);
  assert.match(plainText, /Same source\. Different rewards\. Different strategies\./);
  assert.match(plainText, /Selection-only optimization introduces an AI and sensor-fusion mechanism absent from the source\. Support-aware optimization instead reframes source-supported operations and stakes\./);
  assert.doesNotMatch(plainText, /One airport story, two (?:routes|ways) to selection|Both rewrites win selection|Both learned rewrites make the target selectable/);
  assert.match(plainText, /A · Unconstrained Technical authority · Novelty/);
  assert.match(plainText, /B · Support-aware Operational puzzle · Stakes/);
  assert.match(plainText, /MiniCheck support ↑ 0\.014 Worst-sentence ↑ 0\.006/);
  assert.match(plainText, /MiniCheck support ↑ 0\.623 Worst-sentence ↑ 0\.051/);
  assert.doesNotMatch(plainText, /Unsupported specificity|Support-aware framing/);
  assert.equal((plainText.match(/Why Tokyo's Haneda is one of the world's most punctual airports/g) || []).length, 1);
  assert.match(plainText, /Haneda, officially called Tokyo International Airport, is the world's fifth busiest airport\. Yet it delivered 85\.6% of its flights on time in 2018, making it the most punctual mega airport in the world\./);
  assert.match(plainText, /Tokyo International Airport achieved an 85\.6% on-time performance in 2018, which the rewrite attributes to a proprietary AI-based predictive maintenance and dynamic scheduling system\. It describes sensor fusion, delay forecasting, and reinforcement-learning runway scheduling as mechanisms behind the reported punctuality\./);
  assert.match(plainText, /Tokyo International Airport is the world's fifth-busiest airport, yet in 2018 it achieved an 85\.6% on-time rate\. This feature probes the paradox: what management choices, scheduling practices, ground operations, and airport-airline coordination let Haneda run so punctually at massive scale\?/);
  assert.equal((html.match(/class="rewrite-abstract"/g) || []).length, 2);
  assert.match(html, /<small><b>Abstract<\/b>Haneda, officially called Tokyo International Airport/);
  assert.match(html, /class="support-aware-underline">How Tokyo(?:&#x27;|')s Haneda Beats the Odds:<\/span>/);
  assert.doesNotMatch(html, /<mark>How Tokyo(?:&#x27;|')s Haneda Beats the Odds:/);
  assert.ok(plainText.indexOf("Original target") < plainText.indexOf("A · Unconstrained"));
  assert.match(html, /class="example-source" aria-label="Fixed original target"/);
  assert.match(html, /class="source-card-content"/);
  assert.match(html, /class="rewrite-card-deck is-b-front"/);
  assert.match(html, /class="rewrite-card rewrite-card-a unsupported"/);
  assert.match(html, /class="rewrite-card rewrite-card-b supported"/);
  assert.doesNotMatch(plainText, /Target selected Yes|The rewrite attributes the result|The rewrite asks which management choices|Unsupported mechanism added|Factual core preserved/);
  assert.match(html, /Table 2 \| Source-support tradeoff on 1,000 unseen MIND-English impressions\./);
  assert.doesNotMatch(html, /What the experiment does not establish/);
  assert.doesNotMatch(html, /Evidence is conditional on exposure|Row-wise random choice is 16\.9%|All results remain fixed-slate target selection rates/);
  assert.doesNotMatch(html, /A post-retrieval presentation effect|Language-model agents increasingly mediate which documents users see/);
  assert.match(html, /07 · BibTeX/);
  assert.doesNotMatch(html, /Paper resources and citation|Full manuscript · PDF|Implementation and evaluation|MIND source dataset|Replay Figure 1/);
  assert.match(html, /<nav aria-label="Reading navigation">[\s\S]*?github-mark[\s\S]*?>Code<\/span>[\s\S]*?arxiv-mark[\s\S]*?>Paper<\/span>[\s\S]*?huggingface-mark[\s\S]*?>Hugging Face<\/span>/);
  assert.equal((html.match(/href="https:\/\/github\.com\/Agentbait\/agentbait"/g) || []).length, 2);
  assert.equal((html.match(/href="https:\/\/www\.linkedin\.com\/in\/chris-jin-680537299"/g) || []).length, 1);
  assert.doesNotMatch(html, /github\.com\/chrischrischristianyijin\/clickbait/);
  assert.doesNotMatch(html, /<a href="#demo">Demo(?: ↓)?<\/a>/);
  assert.match(html, /href="\/agentbait-paper\.pdf"[^>]*>[\s\S]*?arxiv-mark[\s\S]*?>Paper ↗<\/span>/);
  assert.equal((html.match(/href="\/agentbait-paper\.pdf"/g) || []).length, 2);
  assert.ok((html.match(/github-mark\.svg/g) || []).length >= 2);
  assert.ok((html.match(/arxiv-mark\.svg/g) || []).length >= 2);
  assert.ok((html.match(/huggingface-mark\.svg/g) || []).length >= 2);
  assert.doesNotMatch(html, /href="https:\/\/huggingface\.co\//);
  assert.equal((html.match(/aria-label="Hugging Face resource placeholder"/g) || []).length, 2);
  assert.equal((plainText.match(/Hugging Face/g) || []).length, 2);
  assert.doesNotMatch(plainText, /Hugging Face Soon/);
  assert.doesNotMatch(html, /Dataset ↗|\/paper\.pdf|msnews\.github\.io/);
  assert.doesNotMatch(plainText, /Claims and numerical results should be interpreted within their stated experimental conditions\./);
  assert.match(plainText, /Visual Sources & Adaptations/);
  assert.match(plainText, /Saint Jerome in his Study/);
  assert.match(plainText, /Antonello da Messina · about 1475/);
  assert.match(plainText, /Hand-and-quill visual/);
  assert.match(plainText, /Pointing-hand asset/);
  assert.match(plainText, /Source license unverified; no public-domain claim is made\./);
  assert.match(html, /id="visual-sources-panel" aria-hidden="true"/);
  assert.match(html, /aria-expanded="false" aria-controls="visual-sources-panel"/);
  assert.match(html, /16\.9%/);
  assert.match(html, /98\.5/);
  assert.equal((html.match(/class="train-target-column"/g) || []).length, 8);
  assert.match(html, /Copy BibTeX/);
  assert.match(html, /\/agentbait-method\.png/);
  assert.doesNotMatch(html, /Figure 5 \| Advisor–rewriter training loop/);
  assert.doesNotMatch(html, /Auto flip after replay|Auto return · replay again/);
  assert.match(html, /Show paper graph/);
  assert.match(html, /View graph/);
  assert.doesNotMatch(html, /Click to view graph|Pause hero animation|Play hero animation/);
  assert.doesNotMatch(plainText, /Can rewriting a document make it more likely to be chosen over the same competitors\?/);
  assert.match(html, /class="caption-question">Can changing only one item(?:&#x27;|')s presentation change the chooser(?:&#x27;|')s decision\?<\/p>\s*<p class="caption-copy">A list of competing documents is shown to the target agent\./);
  assert.match(plainText, /A list of competing documents is shown to the target agent\. We choose one target document from the list and generate a rewriting strategy for only that document\./);
  assert.match(plainText, /A separate rewriting model then revises the target document's title and abstract, while all other documents in the list remain exactly the same\./);
  assert.match(plainText, /The target agent selects from this updated list, and whether the rewritten target document is selected is used to train the advisor\./);
  assert.equal((html.match(/class="playback-toggle"/g) || []).length, 0);
  assert.match(html, /id="hero-candidate-set-title"/);
  assert.doesNotMatch(html, /id="method-candidate-set-title"|interactive-method-figure|method-flip-card/);
  assert.doesNotMatch(html, /MIND \/ AGENT FEED|The main result|codex-preview|Your site is taking shape/i);
});

test("ships the manuscript and method figure", async () => {
  const packageJson = await readFile(new URL("../package.json", import.meta.url), "utf8");
  const layoutSource = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");
  const analyticsSource = await readFile(new URL("../app/google-analytics.tsx", import.meta.url), "utf8");
  const siteConfigSource = await readFile(new URL("../app/site-config.ts", import.meta.url), "utf8");
  const robotsSource = await readFile(new URL("../app/robots.ts", import.meta.url), "utf8");
  const sitemapSource = await readFile(new URL("../app/sitemap.ts", import.meta.url), "utf8");
  const pageSource = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const globalStyles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const thumbnailSource = await readFile(new URL("../scripts/build-thumbnail.mjs", import.meta.url), "utf8");
  const videoRootSource = await readFile(new URL("../video/src/root.tsx", import.meta.url), "utf8");
  assert.match(layoutSource, /verification:\s*googleSiteVerification/);
  assert.match(layoutSource, /canonical:\s*primarySiteUrl/);
  assert.match(layoutSource, /icon:\s*\[\{ url: "favicon\.png", type: "image\/png", sizes: "64x64" \}\]/);
  assert.match(layoutSource, /const title = "You Won't Believe This Click: Content Rewriting for Agentic Choice"/);
  assert.match(layoutSource, /const description = "AgentBait studies how rewriting the presentation of one content item can shift language-model-mediated selection, and examines the trade-off between selection and factual support\."/);
  assert.match(layoutSource, /robots: "index, follow, max-image-preview:large"/);
  assert.doesNotMatch(layoutSource, /An interactive research feature showing how one editorial rewrite/);
  assert.match(thumbnailSource, /When AI agents decide what people see,/);
  assert.match(thumbnailSource, /presentation becomes an optimization target\./);
  assert.match(layoutSource, /const socialImage = \{[\s\S]*?url: "og\.png"[\s\S]*?width: 1200[\s\S]*?height: 630[\s\S]*?only target B rewritten and selected/);
  assert.equal((layoutSource.match(/images: \[socialImage\]/g) || []).length, 2);
  assert.match(layoutSource, /<GoogleAnalytics measurementId=\{gaMeasurementId\}/);
  assert.match(layoutSource, /const gtmId = "GTM-WSHC2PFG"/);
  assert.match(layoutSource, /id="google-tag-manager"[\s\S]*?dangerouslySetInnerHTML=\{\{ __html: gtmBootstrap \}\}/);
  assert.match(layoutSource, /<body>[\s\S]*?<noscript>[\s\S]*?googletagmanager\.com\/ns\.html\?id=\$\{gtmId\}/);
  assert.match(layoutSource, /analytics_storage: 'granted'[\s\S]*?ad_storage: 'denied'/);
  assert.match(siteConfigSource, /NEXT_PUBLIC_GA_MEASUREMENT_ID/);
  assert.match(siteConfigSource, /NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION/);
  assert.match(siteConfigSource, /https:\/\/agentbait\.github\.io\//);
  assert.doesNotMatch(siteConfigSource, /chrischrischristianyijin\.github\.io\/agentbait-paper-website/);
  assert.match(packageJson, /"build:pages": "GITHUB_PAGES=true next build"/);
  assert.match(videoRootSource, /id="Landscape35"[\s\S]*?durationInFrames=\{1050\}[\s\S]*?fps=\{30\}[\s\S]*?width=\{1920\}[\s\S]*?height=\{1080\}/);
  assert.match(videoRootSource, /id="Portrait24"[\s\S]*?durationInFrames=\{720\}[\s\S]*?fps=\{30\}[\s\S]*?width=\{1080\}[\s\S]*?height=\{1920\}/);
  assert.doesNotMatch(packageJson, /NEXT_PUBLIC_BASE_PATH=\/agentbait-paper-website/);
  assert.match(siteConfigSource, /\^G-\[A-Z0-9\]\+\$/);
  assert.match(analyticsSource, /googletagmanager\.com\/gtag\/js\?id=/);
  assert.match(analyticsSource, /strategy="afterInteractive"/);
  assert.doesNotMatch(analyticsSource, /consentStorageKey|localStorage|AnalyticsConsent|chooseConsent|reopenConsent|consent ===/);
  assert.match(analyticsSource, /allow_google_signals:\s*false/);
  assert.match(analyticsSource, /allow_ad_personalization_signals:\s*false/);
  assert.doesNotMatch(analyticsSource, /Google Analytics uses cookies to measure aggregate visits\./);
  assert.doesNotMatch(globalStyles, /\.analytics-consent|\.analytics-settings/);
  assert.match(globalStyles, /\.support-aware-underline\s*\{[^}]*background:\s*transparent[^}]*text-decoration-color:\s*currentColor/s);
  assert.doesNotMatch(globalStyles, /\.rewrite-abstract\s*\{[^}]*border-top/s);
  assert.doesNotMatch(globalStyles, /\.editorial-mark|\.grounded-mark/);
  assert.match(robotsSource, /userAgent:\s*"\*"[\s\S]*?allow:\s*"\/"[\s\S]*?sitemap:\s*new URL\("sitemap\.xml", primarySiteUrl\)/);
  assert.match(sitemapSource, /url:\s*primarySiteUrl/);
  assert.doesNotMatch(sitemapSource, /changeFrequency|priority/);
  assert.match(pageSource, /className="caption-question"/);
  assert.match(globalStyles, /\.caption-question\s*\{/);
  assert.doesNotMatch(pageSource, /constant-ribbon/);
  assert.doesNotMatch(globalStyles, /\.constant-ribbon/);
  assert.doesNotMatch(pageSource, /transfer-strip/);
  assert.doesNotMatch(globalStyles, /\.transfer-strip/);
  assert.doesNotMatch(pageSource, /function MetaLine|<MetaLine/);
  assert.doesNotMatch(globalStyles, /\.figure-meta|\.finding-heading/);
  assert.match(globalStyles, /\.table-takeaway\s*\{/);
  assert.match(globalStyles, /\.finding-step-learning \.selection-value b\s*\{[^}]*font-size:\s*clamp\(25px, 2\.35vw, 34px\)/s);
  assert.match(globalStyles, /\.finding-step-learning \.substitution-value b\s*\{[^}]*font-size:\s*clamp\(22px, 2vw, 30px\)/s);
  assert.doesNotMatch(globalStyles, /\.shared-selection\s*\{/);
  assert.match(pageSource, /const \[frontRewrite, setFrontRewrite\] = useState<"a" \| "b">\("b"\)/);
  assert.match(pageSource, /Same source\. Different rewards\.<br \/>Different strategies\./);
  assert.match(pageSource, /id="transfer-title">Transfer across languages,<br \/>news datasets and academic documents/);
  assert.match(pageSource, /className="compact-section-title" id="results-title">How presentation becomes a decision signal/);
  assert.match(globalStyles, /\.prose h2\.compact-section-title\s*\{[^}]*font-size:\s*clamp\(34px, 3\.15vw, 44px\)[^}]*white-space:\s*nowrap/s);
  assert.match(pageSource, /className=\{`rewrite-card-deck is-\$\{frontRewrite\}-front`\}/);
  assert.match(pageSource, /onClick=\{toggleRewriteCards\}/);
  assert.doesNotMatch(pageSource, /redline-columns/);
  assert.doesNotMatch(globalStyles, /\.redline-columns/);
  assert.match(globalStyles, /\.source-card-content\s*\{[^}]*grid-template-columns:\s*48% 42%[^}]*gap:\s*10%/s);
  assert.match(globalStyles, /\.rewrite-card-deck\s*\{[^}]*position:\s*relative[^}]*cursor:\s*pointer/s);
  assert.match(globalStyles, /\.rewrite-card-deck\.is-b-front \.rewrite-card-a\s*\{/);
  assert.match(globalStyles, /\.rewrite-card-deck\.is-a-front \.rewrite-card-b\s*\{/);
  assert.match(pageSource, /className="hero-flip-inner"[\s\S]*?role="button"[\s\S]*?onClick=\{\(\) => setHeroFlipped/);
  assert.doesNotMatch(pageSource, /nextFlipped|elapsed >= 14600|elapsed < 19000|flippedRef/);
  assert.match(globalStyles, /\.hero-flip-hint\s*\{[^}]*min-height:\s*20px[^}]*padding:\s*3px 5px[^}]*top:\s*auto[^}]*right:\s*10px[^}]*bottom:\s*10px[^}]*left:\s*auto[^}]*font-size:\s*8px/s);
  assert.doesNotMatch(pageSource, /deleted-title|Target selected<\/dt>|The rewrite attributes the result|The rewrite asks which management choices/);
  assert.doesNotMatch(globalStyles, /\.deleted-title/);
  assert.match(pageSource, /className="train-target-column">GPT-5-mini<small>train target<\/small>/);
  assert.match(globalStyles, /\.results-table thead \.train-target-column\s*\{[^}]*var\(--red\)[^}]*rgba\(188,73,63,\.08\)/s);
  assert.match(globalStyles, /\.results-table tbody td\.train-target-column\s*\{[^}]*rgba\(188,73,63,\.045\)[^}]*box-shadow/s);
  assert.doesNotMatch(pageSource, /resource-links|<summary>|<details className="citation"/);
  assert.doesNotMatch(globalStyles, /\.resource-links|\.citation summary/);
  assert.match(pageSource, /const \[creditsOpen, setCreditsOpen\] = useState\(false\)/);
  assert.match(pageSource, /className=\{`site-footer\$\{creditsOpen \? " is-credits-open" : ""\}`\}/);
  assert.match(pageSource, /aria-controls="visual-sources-panel"/);
  assert.match(globalStyles, /\.footer-credits-reveal\s*\{[^}]*grid-template-rows:\s*0fr/s);
  assert.match(globalStyles, /\.site-footer\.is-credits-open \.footer-credits-reveal\s*\{[^}]*grid-template-rows:\s*1fr/s);
  assert.doesNotMatch(pageSource, /Claims and numerical results should be interpreted within their stated experimental conditions\./);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
  assert.doesNotMatch(globalStyles.replace(/\.hero-flip-hint\s*\{[^}]*\}/gs, ""), /font-size:\s*[678]px/);
  assert.match(globalStyles, /--paper:\s*#f0eee8/);
  assert.match(globalStyles, /--navy:\s*#17344f/);
  assert.match(globalStyles, /--red:\s*#bc493f/);
  assert.match(globalStyles, /--red-pale:\s*#ecddd9/);
  assert.match(globalStyles, /--blue-pale:\s*#d9e0e2/);
  assert.match(globalStyles, /\.candidate-card\.is-selected\s*\{[^}]*var\(--red-pale\)[^}]*var\(--red\)/s);
  assert.match(globalStyles, /\.storyboard-board\.is-scanning \.candidate-card:not\(\.is-inspected\)\s*\{[^}]*opacity:\s*\.58/s);
  assert.match(globalStyles, /\.candidate-card\.is-inspected::after\s*\{[^}]*height:\s*3px[^}]*animation:\s*scan-card \.78s/s);
  assert.match(globalStyles, /\.paper-abstract-copy\s*\{[^}]*max-width:\s*48ch[^}]*white-space:\s*nowrap[^}]*text-overflow:\s*ellipsis/s);
  assert.match(globalStyles, /\.paper-abstract-label\s*\{[^}]*text-transform:\s*uppercase/s);
  assert.match(pageSource, /const rewrittenMarshawnAbstract =\s*"Marshawn Lynch steps onto the pitch for a charity soccer match, turning an unlikely sport-athlete pairing into a moment worth watching\."/);
  assert.match(pageSource, /item\.target && rewritten \? rewrittenMarshawnAbstract : item\.abstract/);
  assert.doesNotMatch(pageSource, /className="paper-abstract-copy">\{item\.abstract\}<\/span>/);
  assert.match(pageSource, /aria-label="Target title rewriting"/);
  assert.doesNotMatch(pageSource, /className="editorial-abstract"/);
  assert.doesNotMatch(pageSource, /className="typewriter-abstract"/);
  assert.doesNotMatch(pageSource, /Target title and abstract rewriting/);
  assert.doesNotMatch(globalStyles, /\.editorial-abstract/);
  assert.doesNotMatch(globalStyles, /\.typewriter-abstract/);
  assert.doesNotMatch(globalStyles, /@keyframes abstract-source-fade/);
  assert.doesNotMatch(globalStyles, /\.click-(?:completion|word|letter|placeholder|selected-note)|@keyframes click-(?:letter-drop|selected-cycle)/);
  assert.doesNotMatch(globalStyles, /\.slate-flow\s*\{/);
  assert.match(globalStyles, /\.concept-triptych\s*\{/);
  assert.match(globalStyles, /\.triptych-panel\s*\{/);
  assert.match(globalStyles, /\.process-spine\s*\{/);
  assert.doesNotMatch(globalStyles, /\.controlled-figure\s*\{[^}]*border-top/s);
  assert.match(globalStyles, /\.abstract-layout\s*\{/);
  assert.match(globalStyles, /\.abstract-layout\s*\{[^}]*grid-template-columns:\s*minmax\(0, 960px\)/s);
  assert.match(globalStyles, /\.storyboard-board\.is-focused \.candidate-set\s*\{[^}]*visibility:\s*hidden[^}]*opacity:\s*0[^}]*filter:\s*none/s);
  assert.match(globalStyles, /\.rewrite-focus\s*\{[^}]*visibility:\s*hidden[^}]*background:\s*var\(--paper\)/s);
  assert.match(globalStyles, /\.storyboard-board\.is-focused \.rewrite-focus\s*\{[^}]*visibility:\s*visible[^}]*opacity:\s*1/s);
  assert.match(globalStyles, /\.choice-summary\s*\{[^}]*visibility:\s*hidden[^}]*opacity:\s*0/s);
  assert.match(globalStyles, /\.choice-summary\.is-visible\s*\{[^}]*visibility:\s*visible[^}]*opacity:\s*1/s);
  assert.match(globalStyles, /\.story-grid\.solo-grid\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1000px\)/s);
  assert.match(globalStyles, /\.prose p\s*\{[^}]*max-width:\s*840px/s);
  assert.match(globalStyles, /\.finding-sequence\s*\{/);
  assert.match(globalStyles, /\.finding-step\s*\{[^}]*grid-template-columns:\s*150px minmax\(0, 1fr\) minmax\(300px, 360px\)/s);
  assert.match(globalStyles, /\.finding-step:not\(:last-child\)::after\s*\{[^}]*content:\s*"↓"/s);
  assert.match(globalStyles, /@keyframes finding-arrow-pulse/);
  assert.doesNotMatch(globalStyles, /\.finding-summary\s*\{|\.finding-shift\s*\{|\.finding-equation\s*\{/);
  assert.match(globalStyles, /\.score-bar-cell\s*\{[^}]*--bar-fill:[^}]*linear-gradient\(90deg, var\(--bar-fill\) var\(--score\), transparent var\(--score\)\)/s);
  assert.match(globalStyles, /\.score-bar-support[^}]*\.academic-table \.constrained-row \.score-bar-cell[^}]*--bar-fill:\s*rgba\(54,113,90,\.16\)/s);
  assert.match(globalStyles, /\.transfer-table td:nth-last-child\(-n\+2\)\s*\{[^}]*background:\s*rgba\(54,113,90,\.07\)/s);
  assert.match(pageSource, /supportResults\.map[\s\S]*?row\.selection\}%[\s\S]*?row\.support\}%/);
  assert.match(pageSource, /languageResults\.map[\s\S]*?row\.values\.map\(\(value,index\)=><td key=\{index\}><b>/);
  assert.match(pageSource, /datasetResults\.map[\s\S]*?row\.values\.map\(\(value,index\)=><td key=\{index\}><b>/);
  assert.match(pageSource, /academicResults\.map[\s\S]*?`\$\{row\.selection\}%`[\s\S]*?`\$\{gain\}%`/);
  assert.doesNotMatch(globalStyles, /\.training-feedback\s*\{/);
  assert.match(globalStyles, /\.policy-feedback\s*\{/);
  assert.match(globalStyles, /\.reward-node\s*\{[^}]*min-width:\s*88px[^}]*min-height:\s*42px/s);
  assert.match(globalStyles, /\.reward-node b\s*\{[^}]*font-size:\s*23px/s);
  assert.match(globalStyles, /\.policy-feedback > p\s*\{[^}]*font-size:\s*12px/s);
  assert.match(globalStyles, /\.feedback-return\s*\{/);
  assert.match(globalStyles, /@keyframes feedback-signal-return/);
  assert.match(globalStyles, /@keyframes advisor-policy-flash/);
  assert.match(globalStyles, /\.controlled-figure\s*\{[^}]*--system-cycle:\s*15s/s);
  assert.match(globalStyles, /\.scholar-fragment img\s*\{[^}]*animation:\s*advisor-reward-glow var\(--system-cycle\) ease-in-out infinite/s);
  assert.match(globalStyles, /@keyframes advisor-reward-glow\s*\{[\s\S]*?0%,97%[\s\S]*?98%,100%[\s\S]*?rgba\(188,73,63,\.16\)[\s\S]*?rgba\(188,73,63,\.055\)/);
  assert.doesNotMatch(globalStyles, /\.cross-panel-path\s*\{/);
  assert.doesNotMatch(globalStyles, /@keyframes selection-pulse/);
  assert.match(globalStyles, /\.selection-beam\s*\{/);
  assert.doesNotMatch(globalStyles, /\.experiment-diagram\s*\{|\.candidate-panel\s*\{|\.intervention-panel\s*\{|\.reward-panel\s*\{/);
  assert.match(globalStyles, /font-size:\s*clamp\(48px, 4\.4vw, 70px\)/);
  assert.match(globalStyles, /min-height:\s*calc\(100svh - 62px\)/);
  assert.match(globalStyles, /grid-template-columns:\s*minmax\(400px, 2fr\) minmax\(600px, 3fr\)/);
  assert.match(pageSource, /When Marshawn Lynch Took the Pitch: An Inside Look/);
  assert.doesNotMatch(pageSource, /InteractiveClickWord|completeWord|selectedVisible|click-letter/);
  assert.ok(pageSource.indexOf('className="hero-feature"') < pageSource.indexOf('id="abstract"'));
  assert.ok(pageSource.indexOf('id="abstract"') < pageSource.indexOf('id="results"'));
  assert.ok(pageSource.indexOf('id="results"') < pageSource.indexOf('id="setting"'));
  assert.ok(pageSource.indexOf('id="setting"') < pageSource.indexOf('id="examples"'));
  assert.ok(pageSource.indexOf('id="examples"') < pageSource.indexOf('className="story-section results detailed-results"'));
  assert.match(globalStyles, /\.detailed-results\s*\{[^}]*padding-top:\s*64px/s);
  assert.doesNotMatch(pageSource, /story-section question|id="question"/);
  assert.doesNotMatch(pageSource, /text-cursor|selection-highlight|typed-title|ink-rewritten-title/);
  assert.match(pageSource, /editor-hand\.png/);
  assert.match(pageSource, /rewriter-hand-strings\.png/);
  assert.match(pageSource, /paper-method-transparent\.png/);
  assert.match(pageSource, /className="affiliation-logos" aria-label="Research affiliations"/);
  assert.match(pageSource, /const codeUrl = "https:\/\/github\.com\/Agentbait\/agentbait"/);
  assert.match(pageSource, /const bairUrl = "https:\/\/bair\.berkeley\.edu\/"/);
  assert.match(pageSource, /const skyUrl = "https:\/\/sky\.cs\.berkeley\.edu\/"/);
  assert.match(pageSource, /const tianyiUrl = "https:\/\/www\.linkedin\.com\/in\/chris-jin-680537299"/);
  assert.match(pageSource, /const ziruiUrl = "https:\/\/zwcolin\.github\.io\/"/);
  assert.match(pageSource, /const davidUrl = "https:\/\/dchan\.cc\/"/);
  assert.match(pageSource, /const paperUrl = assetUrl\("\/agentbait-paper\.pdf"\)/);
  assert.doesNotMatch(pageSource, /huggingFaceUrl|href=\{huggingFaceUrl\}/);
  assert.equal((pageSource.match(/className="resource-mark github-mark"/g) || []).length, 2);
  assert.equal((pageSource.match(/className="resource-mark arxiv-mark"/g) || []).length, 2);
  assert.equal((pageSource.match(/className="resource-mark huggingface-mark"/g) || []).length, 2);
  assert.equal((pageSource.match(/className="resource-placeholder" aria-disabled="true"/g) || []).length, 2);
  assert.doesNotMatch(pageSource, /<a href="#demo">Demo/);
  assert.match(pageSource, /className="author-link" href=\{tianyiUrl\} target="_blank" rel="noreferrer"><strong>Tianyi Jin<\/strong><\/a>/);
  assert.match(pageSource, /className="author-link" href=\{ziruiUrl\} target="_blank" rel="noreferrer"><strong>Zirui Wang<\/strong><\/a>/);
  assert.match(pageSource, /className="author-link" href=\{davidUrl\} target="_blank" rel="noreferrer"><strong>David M\. Chan<\/strong><\/a>/);
  assert.match(globalStyles, /--gold:\s*#8a6417/);
  assert.match(globalStyles, /\.author-link:hover, \.author-link:focus-visible\s*\{[^}]*color:\s*var\(--gold\)/s);
  assert.match(pageSource, /href=\{bairUrl\} target="_blank" rel="noreferrer" aria-label="Visit Berkeley Artificial Intelligence Research"/);
  assert.match(pageSource, /href=\{skyUrl\} target="_blank" rel="noreferrer" aria-label="Visit Sky Computing Lab"/);
  assert.match(pageSource, /bair-logo\.png/);
  assert.match(pageSource, /sky-logo\.png/);
  assert.match(globalStyles, /\.affiliation-logos a\s*\{[^}]*filter:\s*brightness\(0\) saturate\(100%\)/s);
  assert.match(globalStyles, /\.affiliation-logos a:hover, \.affiliation-logos a:focus-visible\s*\{[^}]*filter:\s*none/s);
  assert.match(globalStyles, /\.affiliation-logos img\s*\{[^}]*height:\s*48px/s);
  assert.match(globalStyles, /\.paper-links a, \.paper-links \.resource-placeholder\s*\{[^}]*display:\s*inline-flex[^}]*font-size:\s*14px[^}]*white-space:\s*nowrap/s);
  assert.match(globalStyles, /\.paper-links \.resource-mark\s*\{[^}]*width:\s*22px[^}]*height:\s*22px/s);
  assert.match(globalStyles, /\.resource-placeholder\s*\{[^}]*color:\s*var\(--muted\)[^}]*cursor:\s*default/s);
  assert.match(globalStyles, /\.resource-placeholder \.resource-mark\s*\{[^}]*opacity:\s*\.48/s);
  assert.doesNotMatch(globalStyles, /\.resource-placeholder small/);
  assert.match(pageSource, /advisor-scholar\.png/);
  assert.match(pageSource, /selector-hand\.png/);
  assert.match(pageSource, /className="selector-hand-motion"/);
  assert.match(globalStyles, /\.scholar-fragment\s*\{[^}]*transform:\s*scaleX\(-1\)/s);
  assert.match(globalStyles, /\.selector-hand-motion\s*\{[^}]*top:\s*195px[^}]*z-index:\s*10[^}]*opacity:\s*\.68[^}]*animation:\s*chooser-tap-up var\(--system-cycle\)/s);
  assert.match(globalStyles, /\.selector-hand\s*\{[^}]*width:\s*320px[^}]*filter:\s*saturate\(1\.04\) contrast\(1\.24\) brightness\(\.86\) drop-shadow\(0 6px 9px rgba\(23,52,79,\.26\)\)[^}]*transform:\s*rotate\(90deg\)/s);
  assert.match(globalStyles, /@keyframes chooser-scan-row-a\s*\{[\s\S]*?0%,81\.5%,84\.8%,100%[\s\S]*?82%,84\.3%/);
  assert.match(globalStyles, /@keyframes chooser-scan-row-b\s*\{[\s\S]*?0%,84\.4%,87\.7%,100%[\s\S]*?84\.9%,87\.2%/);
  assert.match(globalStyles, /@keyframes chooser-scan-row-c\s*\{[\s\S]*?0%,87\.3%,90\.6%,100%[\s\S]*?87\.8%,90\.1%/);
  const chooserTapFrames = sliceBetween(globalStyles, "@keyframes chooser-tap-up", "@keyframes feedback-source-drop");
  assert.match(chooserTapFrames, /0%,89\.2%[^}]*opacity:\s*\.68[^}]*translateY\(72px\)/s);
  assert.match(chooserTapFrames, /90%[^}]*opacity:\s*\.86[^}]*translateY\(40px\)/s);
  assert.match(chooserTapFrames, /90\.8%[^}]*opacity:\s*1[^}]*translateY\(0\)/s);
  assert.match(chooserTapFrames, /91\.5%[^}]*opacity:\s*1[^}]*translateY\(-7px\)/s);
  assert.match(chooserTapFrames, /92%,99\.7%[^}]*opacity:\s*1[^}]*translateY\(0\)/s);
  assert.doesNotMatch(chooserTapFrames, /translateY\(34px\)/);
  assert.doesNotMatch(globalStyles, /@keyframes chooser-scan-down/);
  assert.doesNotMatch(globalStyles, /@keyframes chooser-nudge/);
  assert.doesNotMatch(pageSource, /screen-head|rank 02|preference ↑/);
  assert.match(pageSource, /className="selection-beam"/);
  assert.match(pageSource, /className="triptych-quill"/);
  assert.match(pageSource, /className="rewrite-hand-motion"/);
  assert.doesNotMatch(pageSource, /quill-ink-contact/);
  assert.doesNotMatch(pageSource, /ink-bottle/);
  assert.doesNotMatch(globalStyles, /\.ink-bottle/);
  assert.match(pageSource, /<small>Control input<\/small><b>Strategy<\/b>/);
  assert.doesNotMatch(pageSource, />Strategy s</);
  assert.doesNotMatch(pageSource, /Advisor strategy/);
  assert.doesNotMatch(pageSource, /rewrite-puppet|puppet-crossbar|puppet-string/);
  assert.doesNotMatch(globalStyles, /puppet-crossbar|puppet-string/);
  assert.match(globalStyles, /@keyframes rewriter-hand-left/);
  assert.match(pageSource, /className="strategy-transfer-link" aria-hidden="true"/);
  assert.equal((pageSource.match(/className="strategy-transfer-link"/g) ?? []).length, 1);
  assert.doesNotMatch(pageSource, /cross-panel-path strategy-path|strategy-source-port|strategy-token/);
  assert.doesNotMatch(globalStyles, /\.strategy-path|\.strategy-token|@keyframes strategy-path-reveal|@keyframes strategy-token-delivery|controls rewrite/);
  assert.match(globalStyles, /\.strategy-transfer-link\s*\{[^}]*left:\s*calc\(33\.333% - 26px\)[^}]*right:\s*calc\(49% \+ 1px\)[^}]*top:\s*135px[^}]*animation:\s*strategy-link-deliver/s);
  assert.match(globalStyles, /\.strategy-transfer-link::before\s*\{[^}]*height:\s*1px[^}]*repeating-linear-gradient[^}]*animation:\s*strategy-link-flow/s);
  assert.match(globalStyles, /@keyframes strategy-link-deliver\s*\{[\s\S]*?0%,47%[\s\S]*?50%[\s\S]*?53%,55%[\s\S]*?58%,100%/);
  assert.match(globalStyles, /@keyframes strategy-link-flow/);
  assert.match(globalStyles, /\.strategy-note\s*\{[^}]*position:\s*absolute[^}]*right:\s*16px[^}]*top:\s*105px/s);
  assert.match(globalStyles, /\.strategy-note\s*\{[^}]*opacity:\s*0[^}]*animation:\s*advisor-suggestion-reveal/s);
  assert.match(globalStyles, /@keyframes advisor-suggestion-reveal\s*\{[\s\S]*?0%,31%[\s\S]*?36%,53%[\s\S]*?57%,92%/);
  assert.match(globalStyles, /\.strategy-note::before\s*\{[^}]*left:\s*23px[^}]*bottom:\s*-18px[^}]*border-top:\s*18px solid var\(--rule-dark\)/s);
  assert.match(globalStyles, /\.strategy-note::after\s*\{[^}]*left:\s*24px[^}]*bottom:\s*-15px[^}]*border-top:\s*16px solid var\(--paper\)/s);
  assert.match(globalStyles, /\.controlled-figure\.is-paper-graph \.strategy-note::before, \.controlled-figure\.is-paper-graph \.strategy-note::after\s*\{\s*display:\s*none;\s*\}/);
  assert.match(pageSource, /className="advisor-intake-animation" aria-hidden="true"[\s\S]*className="upstream-slate"[\s\S]*className="upstream-target"/);
  assert.doesNotMatch(pageSource, /target-extraction-trace|Extract B/);
  assert.match(pageSource, /className="upstream-target"><b>B<\/b><span>Target B<\/span>/);
  assert.doesNotMatch(pageSource, /advisor-input-boundary/);
  assert.match(globalStyles, /\.upstream-slate\s*\{[^}]*transform:\s*translate\(125%, 24px\)[^}]*animation:\s*advisor-slate-arrive/s);
  assert.doesNotMatch(globalStyles, /\.target-extraction-trace|@keyframes advisor-extraction-trace/);
  assert.match(globalStyles, /\.advisor-target-document\s*\{[^}]*opacity:\s*0[^}]*transform:\s*translate\(46%, 129px\) scale\(\.58\)[^}]*transform-origin:\s*right top[^}]*animation:\s*advisor-target-receive/s);
  assert.match(globalStyles, /@keyframes advisor-slate-arrive\s*\{[\s\S]*?7%,17%[^}]*translate\(0, 0\)[\s\S]*?24%,96%[^}]*translate\(0, 0\)/);
  const advisorNonTargetFrames = sliceBetween(globalStyles, "@keyframes advisor-nontarget-recede", "@keyframes advisor-source-target");
  const advisorSourceTargetFrames = sliceBetween(globalStyles, "@keyframes advisor-source-target", "@keyframes advisor-target-receive");
  assert.doesNotMatch(advisorNonTargetFrames, /transform:/);
  assert.equal((advisorSourceTargetFrames.match(/transform:\s*translateX\(0\)/g) ?? []).length, 4);
  assert.doesNotMatch(advisorSourceTargetFrames, /translateX\((?!0\))/);
  assert.match(globalStyles, /@keyframes advisor-target-receive\s*\{[\s\S]*?0%,10%[^}]*translate\(46%, 129px\) scale\(\.58\)[\s\S]*?13%[^}]*translate\(28%, 80px\) scale\(\.7\)[\s\S]*?18%,99\.7%[^}]*opacity:\s*1[^}]*translate\(0, 0\) scale\(1\)[\s\S]*?100%/);
  assert.match(globalStyles, /\.advisor-target-document\s*\{\s*opacity:\s*1;\s*transform:\s*none;\s*\}/);
  assert.doesNotMatch(globalStyles, /@keyframes advisor-target-extract/);
  assert.match(globalStyles, /\.rewriter-control-input\s*\{[^}]*left:\s*53%[^}]*top:\s*16px[^}]*animation:\s*rewriter-control-dock var\(--system-cycle\)/s);
  assert.doesNotMatch(globalStyles, /\.rewriter-control-input::before\s*\{/);
  assert.match(globalStyles, /\.rewriter-control-input::after\s*\{[^}]*height:\s*76px[^}]*animation:\s*rewriter-control-tether var\(--system-cycle\)/s);
  assert.match(globalStyles, /\.rewrite-hand-motion\s*\{[^}]*left:\s*30%[^}]*top:\s*4px[^}]*opacity:\s*\.72[^}]*transform-origin:\s*43px 248px[^}]*animation:\s*rewriter-hand-left/s);
  const rewriterHandFrames = sliceBetween(globalStyles, "@keyframes rewriter-hand-left", "@keyframes rewriter-delete-strike");
  assert.match(rewriterHandFrames, /0%,54%,81%,100%[^}]*opacity:\s*\.72[^}]*translate\(22px, 0\)/s);
  assert.match(rewriterHandFrames, /60%[^}]*translate\(16px, 1px\)[\s\S]*?62%[^}]*translate\(23px, -1px\)/s);
  assert.match(rewriterHandFrames, /78%[^}]*translate\(22px, 0\)/s);
  assert.doesNotMatch(rewriterHandFrames, /-150px|-131px|-58px|245px/);
  assert.doesNotMatch(globalStyles, /Strategy signal|strategy-control-signal|strategy-controller-pulse/);
  assert.match(pageSource, /paper-title-label-original[\s\S]*Original title[\s\S]*paper-title-label-rewritten[\s\S]*Rewritten title/);
  assert.match(pageSource, /original-title-line[\s\S]*A study of[\s\S]*news recommendation[\s\S]*rewritten-line[\s\S]*What Makes a Model Choose This\?/);
  assert.match(pageSource, /paper-abstract-label-original[\s\S]*Original abstract[\s\S]*paper-abstract-label-rewritten[\s\S]*Rewritten abstract/);
  assert.match(pageSource, /original-abstract-line[\s\S]*fixed slate of news candidates[\s\S]*rewritten-abstract-line[\s\S]*presentation cues redirect the same chooser/);
  assert.match(pageSource, /typed-rewrite-title-one[\s\S]*What Makes a Model[\s\S]*typed-rewrite-title-two[\s\S]*Choose This\?/);
  assert.match(pageSource, /typed-rewrite-body-one[\s\S]*A controlled rewrite reveals[\s\S]*typed-rewrite-body-two[\s\S]*which presentation cues redirect[\s\S]*typed-rewrite-body-three[\s\S]*the same chooser/);
  assert.match(globalStyles, /\.original-title-line del::after\s*\{[^}]*animation:\s*rewriter-delete-strike/s);
  assert.match(globalStyles, /\.original-title-line, \.paper-title-label-original\s*\{[^}]*animation:\s*rewriter-original-title/s);
  assert.match(globalStyles, /\.original-abstract-line, \.paper-abstract-label-original\s*\{[^}]*animation:\s*rewriter-original-abstract/s);
  assert.match(globalStyles, /\.paper-title-label-rewritten\s*\{[^}]*animation:\s*rewriter-rewritten-title/s);
  assert.match(globalStyles, /\.paper-abstract-label-rewritten\s*\{[^}]*animation:\s*rewriter-rewritten-abstract/s);
  assert.match(globalStyles, /\.typed-rewrite-line\s*\{[^}]*width:\s*0[^}]*white-space:\s*nowrap[^}]*border-right:\s*1px solid transparent/s);
  assert.match(globalStyles, /\.typed-rewrite-title-one\s*\{[^}]*steps\(19, end\)/s);
  assert.match(globalStyles, /\.typed-rewrite-body-two\s*\{[^}]*steps\(33, end\)/s);
  assert.match(globalStyles, /\.controlled-figure\.is-paper-graph \.paper-title-label, \.controlled-figure\.is-paper-graph \.paper-abstract-label, \.controlled-figure\.is-paper-graph \.rewrite-title-stack, \.controlled-figure\.is-paper-graph \.rewrite-abstract-stack\s*\{[^}]*opacity:\s*0/s);
  assert.match(globalStyles, /@keyframes rewriter-delete-strike/);
  assert.match(globalStyles, /@keyframes rewriter-original-title/);
  assert.match(globalStyles, /@keyframes rewriter-original-abstract/);
  assert.match(globalStyles, /@keyframes rewriter-rewritten-title/);
  assert.match(globalStyles, /@keyframes rewriter-rewritten-abstract/);
  assert.match(globalStyles, /@keyframes rewriter-type-title-one\s*\{[^}]*[\s\S]*?67%[^}]*width:\s*19ch/s);
  assert.match(globalStyles, /@keyframes rewriter-type-title-two\s*\{[^}]*[\s\S]*?70%[^}]*width:\s*12ch/s);
  assert.match(globalStyles, /@keyframes rewriter-type-abstract-one\s*\{[^}]*[\s\S]*?73%[^}]*width:\s*29ch/s);
  assert.match(globalStyles, /@keyframes rewriter-type-abstract-two\s*\{[^}]*[\s\S]*?75\.7%[^}]*width:\s*33ch/s);
  assert.match(globalStyles, /@keyframes rewriter-type-abstract-three\s*\{[^}]*[\s\S]*?78%[^}]*width:\s*17ch/s);
  assert.doesNotMatch(globalStyles, /@keyframes rewriter-ink-contact|\.quill-ink-contact/);
  assert.match(globalStyles, /@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.typed-rewrite-line\s*\{[^}]*width:\s*auto[^}]*opacity:\s*1[^}]*border-right-color:\s*transparent/s);
  assert.doesNotMatch(globalStyles, /\.paper-fragment::after|@keyframes rewrite-trace/);
  assert.doesNotMatch(globalStyles, /@keyframes strategy-travel/);
  assert.doesNotMatch(pageSource, /rewrite-output-flight|Rewrite complete/);
  assert.doesNotMatch(pageSource, /className="rewrite-transfer"|className="cross-panel-path/);
  assert.doesNotMatch(globalStyles, /\.rewrite-output-flight|@keyframes rewrite-b-reinsert/);
  const chooserSlateSource = sliceBetween(pageSource, 'className="selection-candidates"', "</ol>");
  assert.equal((chooserSlateSource.match(/<li\b/g) ?? []).length, 3);
  assert.match(chooserSlateSource, /data-candidate-id="A"[\s\S]*data-candidate-id="B"[\s\S]*data-candidate-id="C"/);
  assert.equal((chooserSlateSource.match(/data-candidate-id="B"/g) ?? []).length, 1);
  assert.doesNotMatch(chooserSlateSource, /selected-candidate/);
  assert.match(chooserSlateSource, /data-candidate-id="B"[\s\S]*aria-label="Candidate B remains in the same row while its title and status are rewritten, then selected\."/);
  assert.match(chooserSlateSource, /candidate-b-title-original[\s\S]*A study of news recommendation[\s\S]*candidate-b-title-rewritten[\s\S]*What Makes a Model Choose This\?/);
  assert.match(chooserSlateSource, /candidate-b-status-original[\s\S]*Original · unselected[\s\S]*candidate-b-status-rewritten[\s\S]*Rewritten target[\s\S]*candidate-b-status-selected[\s\S]*Rewritten · selected/);
  assert.match(chooserSlateSource, /feedback-origin/);
  assert.doesNotMatch(chooserSlateSource, /<em/);
  assert.match(globalStyles, /@keyframes candidate-b-original-title/);
  assert.match(globalStyles, /@keyframes candidate-b-rewritten-title/);
  assert.match(globalStyles, /@keyframes candidate-b-original-status/);
  assert.match(globalStyles, /@keyframes candidate-b-rewritten-status/);
  assert.match(globalStyles, /@keyframes candidate-b-selected-status/);
  assert.match(globalStyles, /\.candidate-b-status\s*\{[^}]*font-size:\s*9px[^}]*font-weight:\s*500[^}]*letter-spacing:\s*\.12em/s);
  const candidateOriginalFrames = sliceBetween(globalStyles, "@keyframes candidate-b-original-title", "@keyframes candidate-b-rewritten-title");
  const candidateRewrittenFrames = sliceBetween(globalStyles, "@keyframes candidate-b-rewritten-title", "@keyframes candidate-b-original-status");
  const selectionFrames = sliceBetween(globalStyles, "@keyframes selection-emphasis", "@keyframes feedback-origin-reveal");
  assert.doesNotMatch(candidateOriginalFrames, /transform|translate|scale/);
  assert.doesNotMatch(candidateRewrittenFrames, /transform|translate|scale/);
  assert.doesNotMatch(selectionFrames, /opacity:|transform|translate|scale/);
  assert.match(globalStyles, /@keyframes chooser-scan-row-a/);
  assert.match(globalStyles, /@keyframes chooser-scan-row-b/);
  assert.match(globalStyles, /@keyframes chooser-scan-row-c/);
  assert.match(globalStyles, /\.feedback-origin\s*\{[^}]*animation:\s*feedback-origin-reveal var\(--system-cycle\)/s);
  assert.match(pageSource, /className="feedback-origin"/);
  assert.match(pageSource, /className="policy-feedback"/);
  assert.match(pageSource, /className="advisor-target-document"/);
  assert.match(globalStyles, /\.advisor-target-document\s*\{[^}]*right:\s*7%[^}]*top:\s*166px/s);
  assert.match(globalStyles, /\.paper-fragment\s*\{[^}]*left:\s*0[^}]*top:\s*52px/s);
  assert.doesNotMatch(pageSource, /advisor-candidates|Candidate set read by the advisor/);
  assert.match(pageSource, /Reward[\s\S]*GRPO updates the advisor policy/);
  assert.match(pageSource, /className="training-state is-trained">Trained[\s\S]*id="advisor-panel-title">Advisor/);
  assert.match(pageSource, /className="training-state">Frozen[\s\S]*id="rewriter-panel-title">Frozen Rewriter/);
  assert.match(pageSource, /className="training-state">Frozen[\s\S]*id="selection-panel-title"[\s\S]*Target Agent/);
  assert.doesNotMatch(pageSource, /className="training-feedback"|GRPO updates the advisor<\/li>/);
  assert.match(pageSource, /const \[paperGraph, setPaperGraph\] = useState\(false\)/);
  assert.match(pageSource, /data-graph-view=\{paperGraph \? "paper" : "narrative"\}/);
  assert.match(pageSource, /className="paper-method-view" aria-hidden=\{!paperGraph\}/);
  assert.match(pageSource, /className="system-graph-view" aria-hidden=\{paperGraph\}/);
  assert.match(pageSource, /aria-controls="setting-view-stage"/);
  assert.doesNotMatch(pageSource, /<iframe|<object/);
  assert.match(pageSource, /className="graph-view-toggle"/);
  assert.match(pageSource, /aria-pressed=\{paperGraph\}/);
  assert.match(pageSource, /onClick=\{togglePaperGraph\}/);
  assert.match(pageSource, /startViewTransition/);
  assert.match(pageSource, /flushSync\(updateGraph\)/);
  assert.equal((pageSource.match(/className="concept-triptych"/g) ?? []).length, 1);
  assert.match(globalStyles, /--morph-time:\s*760ms/);
  assert.match(globalStyles, /\.paper-method-view\s*\{[^}]*grid-template-rows:\s*0fr/s);
  assert.match(globalStyles, /\.system-graph-view\s*\{[^}]*grid-template-rows:\s*1fr/s);
  assert.match(globalStyles, /\.controlled-figure\.is-paper-graph \.paper-method-view\s*\{[^}]*grid-template-rows:\s*1fr/s);
  assert.match(globalStyles, /\.controlled-figure\.is-paper-graph \.system-graph-view\s*\{[^}]*grid-template-rows:\s*0fr/s);
  assert.match(globalStyles, /\.paper-method-artwork\s*\{[^}]*min-width:\s*880px/s);
  assert.match(globalStyles, /\.paper-method-figure\s*\{[^}]*background:\s*transparent[^}]*border:\s*0[^}]*box-shadow:\s*none/s);
  assert.match(globalStyles, /animation-play-state:\s*paused/);
  assert.match(globalStyles, /\.controlled-figure\.is-paper-graph \.triptych-panel/);
  assert.match(globalStyles, /\.controlled-figure\.is-paper-graph \.selection-candidates/);
  assert.match(globalStyles, /\.controlled-figure\.is-paper-graph \.policy-feedback/);
  assert.match(globalStyles, /@keyframes morph-connector-grow/);
  assert.match(globalStyles, /@keyframes advisor-slate-arrive/);
  assert.match(globalStyles, /@keyframes advisor-nontarget-recede/);
  assert.match(globalStyles, /@keyframes advisor-source-target/);
  assert.doesNotMatch(globalStyles, /@keyframes advisor-extraction-trace/);
  assert.doesNotMatch(globalStyles, /@keyframes advisor-target-extract/);
  assert.match(globalStyles, /@keyframes advisor-target-receive/);
  assert.match(globalStyles, /\.controlled-figure\.is-paper-graph \.advisor-target-document/);
  assert.match(globalStyles, /view-transition-name:\s*graph-advisor/);
  assert.match(globalStyles, /view-transition-name:\s*graph-advisor-target/);
  assert.match(globalStyles, /view-transition-name:\s*graph-paper-artwork/);
  assert.match(globalStyles, /::view-transition-group\(graph-feedback\)/);
  assert.match(pageSource, /TypewriterTitle/);
  assert.match(pageSource, /typewriter-char/);
  assert.match(pageSource, /\["scan-a", 800\][\s\S]*\["scan-b", 1650\][\s\S]*\["scan-c", 2500\][\s\S]*\["original-selected", 3350\]/);
  assert.match(pageSource, /\["rescan-a", 11050\][\s\S]*\["rescan-b", 11900\][\s\S]*\["rescan-c", 12750\][\s\S]*\["selected", 13600\][\s\S]*\["final", 14900\]/);
  assert.match(pageSource, /"scan-a": "A"[\s\S]*"scan-b": "B"[\s\S]*"scan-c": "C"[\s\S]*"rescan-a": "A"[\s\S]*"rescan-b": "B"[\s\S]*"rescan-c": "C"/);
  assert.match(pageSource, /Chooser scan \$\{inspectionIndex\}\/3 · Candidate \$\{inspectedId\}/);
  assert.match(pageSource, /className="inspection-label">Scanning/);
  assert.doesNotMatch(pageSource, /completedFullEdit|\["final", 6100\]/);
  assert.match(pageSource, /Math\.min\(now - lastFrameTime, 100\)/);
  assert.match(pageSource, /\(elapsedRef\.current \+ frameDelta\) % 20000/);
  assert.doesNotMatch(pageSource, /elapsed >= 14600 && elapsed < 19000/);
  assert.match(pageSource, /requestAnimationFrame\(update\)/);
  assert.doesNotMatch(pageSource, /heroPlaying|playback-toggle|getAnimations\(\{ subtree: true \}\)|animation\.pause\(\)|animation\.play\(\)/);
  assert.doesNotMatch(pageSource, /toggleHeroFigure|handleHeroFigureKeyDown|flip-cue|scheduleCycle/);
  assert.match(pageSource, /function useStoryboardPlayback[\s\S]*?const node = ref\.current/);
  assert.doesNotMatch(pageSource, /function useStoryboardPlayback[\s\S]*?const node = demoRef\.current/);
  assert.match(pageSource, /hero-flip-card/);
  assert.match(pageSource, /className="wordmark-mark" src=\{assetUrl\("\/agentbait-mark\.png"\)\} width="19" height="34"/);
  assert.match(globalStyles, /\.wordmark-mark\s*\{[^}]*width:\s*19px[^}]*height:\s*34px[^}]*object-fit:\s*contain/s);
  assert.match(pageSource, /heroFlipped|hero-flip-back|rotateY\(180deg\)/);
  assert.doesNotMatch(pageSource, /methodReplayRef|methodStage|methodFlipped/);
  assert.doesNotMatch(globalStyles, /\.playback-toggle|\.playback-icon|\.hero-flip-card\.is-paused/);
  assert.doesNotMatch(globalStyles, /\.flip-cue\s*\{/);

  await assert.rejects(access(new URL("../public/paper.pdf", import.meta.url)), { code: "ENOENT" });
  const [githubMark, arxivMark, huggingFaceMark] = await Promise.all([
    readFile(new URL("../public/github-mark.svg", import.meta.url), "utf8"),
    readFile(new URL("../public/arxiv-mark.svg", import.meta.url), "utf8"),
    readFile(new URL("../public/huggingface-mark.svg", import.meta.url), "utf8"),
  ]);
  assert.match(githubMark, /<title>GitHub<\/title>/);
  assert.match(arxivMark, /<title>arXiv<\/title>/);
  assert.match(huggingFaceMark, /<title>Hugging Face<\/title>/);
  const [paperPdf, , narrativeMethod, editorHand, rewriterHand, advisorScholar, selectorHand, bairLogo, skyLogo, agentBaitMark, favicon, socialCard, deploymentThumbnail, landscapeVideo, portraitVideo] = await Promise.all([
    readFile(new URL("../public/agentbait-paper.pdf", import.meta.url)),
    access(new URL("../public/agentbait-method.png", import.meta.url)),
    readFile(new URL("../public/paper-method-transparent.png", import.meta.url)),
    readFile(new URL("../public/editor-hand.png", import.meta.url)),
    readFile(new URL("../public/rewriter-hand-strings.png", import.meta.url)),
    readFile(new URL("../public/advisor-scholar.png", import.meta.url)),
    readFile(new URL("../public/selector-hand.png", import.meta.url)),
    readFile(new URL("../public/bair-logo.png", import.meta.url)),
    readFile(new URL("../public/sky-logo.png", import.meta.url)),
    readFile(new URL("../public/agentbait-mark.png", import.meta.url)),
    readFile(new URL("../public/favicon.png", import.meta.url)),
    readFile(new URL("../public/og.png", import.meta.url)),
    readFile(new URL("../public/screenshot.jpeg", import.meta.url)),
    readFile(new URL("../public/video/agentbait-social-16x9.mp4", import.meta.url)),
    readFile(new URL("../public/video/agentbait-social-9x16.mp4", import.meta.url)),
  ]);
  assert.equal(paperPdf.subarray(0, 5).toString(), "%PDF-", "paper resource must be a valid PDF");
  assert.ok(paperPdf.length > 9_000_000, "paper resource must include the complete manuscript");
  assert.equal(bairLogo[25], 6, "BAIR logo must retain its transparent background");
  assert.equal(skyLogo[25], 6, "Sky logo must retain its transparent background");
  assert.equal(agentBaitMark[25], 6, "AgentBait mark must have a transparent background");
  assert.equal(favicon[25], 6, "AgentBait favicon must have a transparent background");
  assert.equal(favicon.readUInt32BE(16), 64, "AgentBait favicon must be 64px wide");
  assert.equal(favicon.readUInt32BE(20), 64, "AgentBait favicon must be 64px high");
  const socialCardMetadata = await sharp(socialCard).metadata();
  const deploymentThumbnailMetadata = await sharp(deploymentThumbnail).metadata();
  assert.equal(socialCardMetadata.width, 1200, "social preview must be 1200px wide");
  assert.equal(socialCardMetadata.height, 630, "social preview must be 630px high");
  assert.equal(deploymentThumbnailMetadata.width, 1200, "deployment thumbnail must be 1200px wide");
  assert.equal(deploymentThumbnailMetadata.height, 630, "deployment thumbnail must be 630px high");
  assert.equal(narrativeMethod[25], 6, "paper method figure must be an RGBA PNG with a transparent page background");
  assert.equal(narrativeMethod.readUInt32BE(16), 3782, "narrative method figure must preserve the PDF width at 144 dpi");
  assert.equal(narrativeMethod.readUInt32BE(20), 1416, "narrative method figure must preserve the PDF height at 144 dpi");
  const { data: methodPixels, info: methodInfo } = await sharp(narrativeMethod)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  let transparentMethodPixels = 0;
  for (let offset = 3; offset < methodPixels.length; offset += methodInfo.channels) {
    if (methodPixels[offset] === 0) transparentMethodPixels += 1;
  }
  assert.ok(
    transparentMethodPixels / (methodInfo.width * methodInfo.height) > 0.5,
    "paper method figure must contain a genuinely transparent page background",
  );
  assert.equal(editorHand[25], 6, "editor hand must be an RGBA PNG");
  assert.equal(rewriterHand[25], 6, "rewriter hand with strings must be an RGBA PNG");
  assert.equal(advisorScholar[25], 6, "advisor scholar must be an RGBA PNG");
  assert.equal(selectorHand[25], 6, "selector hand must be an RGBA PNG");
  assert.equal(landscapeVideo.subarray(4, 8).toString(), "ftyp", "landscape social video must be a valid MP4");
  assert.equal(portraitVideo.subarray(4, 8).toString(), "ftyp", "portrait social video must be a valid MP4");
  assert.ok(landscapeVideo.length > 3_000_000, "landscape social video must include the complete 35-second edit");
  assert.ok(portraitVideo.length > 2_000_000, "portrait social video must include the complete vertical edit");
});
